### ISSUE TITLE
[meta] New strategies

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-strategies#41]
- [x] https://github.com/EA31337/Strategy-TMA_CG
- [ ] https://github.com/EA31337/Strategy-BB_SVE_BB
- [ ] https://github.com/EA31337/Strategy-TMA_Bands_RSI_True
- [ ] https://github.com/EA31337/Strategy-TMA_Bands_MTF
- [ ] https://github.com/EA31337/Strategy-Hull_MA_MTR
- [ ] https://github.com/EA31337/Strategy-Volume_Price_Change
- [ ] https://github.com/EA31337/Strategy-CCI_Arrows
- [ ] https://github.com/EA31337/Strategy-SR
